services:
  projectsplanner:
    image: projectsplanner
    build:
      context: .
      dockerfile: ProjectsPlanner/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
      - redis-cache
      - redis-queue
  
  projectsloader:
    image: projectsloader
    environment:
      - FILES_PATH=/data/projectloader/files
    volumes:
      - projectloader-data:/data/projectloader/files
    build:
      context: .
      dockerfile: ProjectLoader/Dockerfile
    depends_on:
      - redis-queue
  
  scaninvoker:
    image: scaninvoker
    environment:
      - FILES_PATH=/data/projectloader/files
    volumes:
      - projectloader-data:/data/projectloader/files
    build:
      context: .
      dockerfile: ScanInvoker/Dockerfile
    depends_on:
      - redis-queue
      

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterkey
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    restart: unless-stopped
    command: ["redis-server", "--port", "6379"]
    ports:
      - "6379:6379"

  redis-queue:
    image: redis:latest
    container_name: redis-queue
    restart: unless-stopped
    command: ["redis-server", "--port", "6380"]
    ports:
      - "6380:6380"

volumes:
  postgres_data:
  projectloader-data: