services:
  projectsloader:
    image: projectsloader
    build:
      context: .
      dockerfile: ProjectsPlanner/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
      - redis-cache
      - redis-queue

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterkey
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"

  redis-queue:
    image: redis:latest
    container_name: redis-queue
    restart: unless-stopped
    ports:
      - "6380:6379"

volumes:
  postgres_data: