// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Storages.EntitiesStorage;

#nullable disable

namespace Storages.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20241011222753_ADD_NEW_TABLE_GITHUBPROJECTS")]
    partial class ADD_NEW_TABLE_GITHUBPROJECTS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Contracts.Entities.GitHubProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.Property<string>("UrlPostfix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WebFramework")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GitHubProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
